volumes:
  bundle_data:
  node_modules:
  db-data:

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: myapp_web
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/myapp/node_modules
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome

  db:
    image: postgres:18
    container_name: myapp_db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"